apiVersion: v2
name: newrelic-wrapper
description: A wrapper chart for New Relic nri-bundle
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: nri-bundle
    version: 5.0.0
    repository: https://helm-charts.newrelic.com
    # We alias it to ensure values map correctly, though 'nri-bundle' is the default name
    alias: nri-bundle
